name: Collect Oura Ring Data

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9 AM UTC daily
  workflow_dispatch:      # Allows manual triggering
  
jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Install Wrangler
      run: |
        npm install -g wrangler
        
    - name: Configure Wrangler
      run: |
        echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
        echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
    
    - name: Run data collection script
      env:
        OURA_TOKEN: ${{ secrets.OURA_TOKEN }}
        WORKERS_KV_NAMESPACE_ID: ${{ secrets.WORKERS_KV_NAMESPACE_ID }}
      run: python data-gather/collect_oura_data.py