name: Collect Oura Data

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      target_date:
        description: 'Date to collect data for (YYYY-MM-DD)'
        required: false
        default: ''

# No 'permissions' block is needed anywhere in this file.

jobs:
  collect-and-store:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run collection script
      id: collection_step
      env:
        # Cloudflare Secrets
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_D1_DB: ${{ secrets.CLOUDFLARE_D1_DB }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

        # Oura OAuth2 Secrets
        OURA_CLIENT_ID: ${{ secrets.OURA_CLIENT_ID }}
        OURA_CLIENT_SECRET: ${{ secrets.OURA_CLIENT_SECRET }}
        OURA_REFRESH_TOKEN: ${{ secrets.OURA_REFRESH_TOKEN }}
        
        # Target date input
        TARGET_DATE: ${{ github.event.inputs.target_date }}
      run: python data-gather/collect_oura_data.py

    - name: Update GitHub Secret with new Oura Refresh Token
      if: steps.collection_step.outputs.new_refresh_token != ''
      env:
        # <<< CHANGE: Use the new PAT for authentication >>>
        GH_TOKEN: ${{ secrets.ACTIONS_PAT_FOR_SECRETS }}
        NEW_REFRESH_TOKEN: ${{ steps.collection_step.outputs.new_refresh_token }}
      run: |
        echo "A new Oura refresh token was generated. Updating the GitHub secret..."
        gh secret set OURA_REFRESH_TOKEN --body "$NEW_REFRESH_TOKEN"
        echo "Secret 'OURA_REFRESH_TOKEN' has been updated."
