name: Collect Oura Ring Data

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9 AM UTC daily
  workflow_dispatch:
    inputs:
      target_date:
        description: 'Target date (YYYY-MM-DD format)'
        required: false
        default: ''

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Configure Wrangler
        # Make secrets available as environment variables
        run: |
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_D1_DB=${{ secrets.CLOUDFLARE_D1_DB }}" >> $GITHUB_ENV

      - name: Run Oura data collection
        env:
          OURA_TOKEN: ${{ secrets.OURA_TOKEN }}  # needed by the script
          # CLOUDFLARE_D1_DB, CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID are already in $GITHUB_ENV
        run: |
          # Pass target_date if user triggers a manual workflow dispatch with an input
          if [ "${{ github.event.inputs.target_date }}" != "" ]; then
            python data-gather/collect_oura_data.py "${{ github.event.inputs.target_date }}"
          else
            python data-gather/collect_oura_data.py
          fi
