name: Collect Oura Data

on:
  schedule:
    - cron: '0 9 * * *'  # Run at 9am daily
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to collect data for (YYYY-MM-DD)'
        required: false
        type: string

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run data collection script
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          OURA_TOKEN: ${{ secrets.OURA_TOKEN }}
          TARGET_DATE: ${{ github.event.inputs.date }}
        run: python data-gather/collect_oura_data.py