name: Collect Oura Data

on:
  schedule:
    - cron: '0 9 * * *' # Trigger daily at 9 AM UTC
  workflow_dispatch:
    inputs:
      date:
        description: 'Enter the date for which to fetch data (YYYY-MM-DD)'
        required: false
        default: ''

jobs:
  collect_oura_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests sqlite3

      - name: Run data collection script
        run: |
          if [ -n "${{ github.event.inputs.date }}" ]; then
            python data-gather/collect_oura_data.py --date ${{ github.event.inputs.date }}
          else
            python data-gather/collect_oura_data.py
          fi
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          OURA_TOKEN: ${{ secrets.OURA_TOKEN }}